sudo: required
dist: trusty
git:
  submodules: false
language: c
compiler: gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y nasm texinfo libmpfr-dev libmpc-dev libgmp-dev libisl-dev
  sshpass
script:
- cd $TOPDIR
- wget https://www.lankes.org/deploy/bootstrap.tar.gz
- tar xzf bootstrap.tar.gz
- mkdir -p $TOPDIR/tmp/newlib
- cd $TOPDIR/tmp/bootstrap
- $TOPDIR/RWTH-OS/newlib/configure --target=x86_64-hermit --prefix=$TOPDIR/x86 --disable-shared --disable-multilib --enable-lto --enable-newlib-hw-fp --enable-newlib-io-c99-formats --enable-newlib-multithread
- make -j2
- make install
after_success:
- cd $TOPDIR
- rm -rf tmp/newlib/*
- tar -czf newlib.tar.gz tmp x86
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no newlib.tar.gz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH 2> /dev/null
env:
   global:
     - TOPDIR=`pwd`/../..
     - PATH=$PATH:$TOPDIR/x86/bin
     - CROSSCOMPREFIX = x86_64-hermit
     - STACKPROT = -fno-stack-protector
     - FC_FOR_TARGET = $CROSSCOMPREFIX-gfortran
     - CC_FOR_TARGET = $CROSSCOMPREFIX-gcc
     - CXX_FOR_TARGET = $CROSSCOMPREFIX-g++
     - GCC_FOR_TARGET = $CROSSCOMPREFIX-gcc
     - CPP_FOR_TARGET = $CROSSCOMPREFIX-cpp
     - AR_FOR_TARGET = $CROSSCOMPREFIX-ar
     - AS_FOR_TARGET = $CROSSCOMPREFIX-as
     - LD_FOR_TARGET = $CROSSCOMPREFIX-ld
     - NM_FOR_TARGET = $CROSSCOMPREFIX-nm
     - OBJDUMP_FOR_TARGET = $CROSSCOMPREFIX-objdump
     - OBJCOPY_FOR_TARGET = $CROSSCOMPREFIX-objcopy
     - RANLIB_FOR_TARGET = $CROSSCOMPREFIX-ranlib
     - STRIP_FOR_TARGET = $CROSSCOMPREFIX-strip
     - READELF_FOR_TARGET = $CROSSCOMPREFIX-readelf
     - ELFEDIT_FOR_TARGET = $CROSSCOMPREFIX-elfedit
     - CFLAGS_FOR_TARGE = -m64 -mtls-direct-seg-refs -mno-red-zone -O3 -march=native -mtune=native -ftree-vectorize $STACKPROT
     - FCFLAGS_FOR_TARGET = -m64 -mtls-direct-seg-refs -mno-red-zone -O3 -march=native -mtune=native -ftree-vectorize
     - FFLAGS_FOR_TARGET = -m64 -mtls-direct-seg-refs -mno-red-zone -O3 -march=native -mtune=native -ftree-vectorize
     - CXXFLAGS_FOR_TARGET = -m64 -mtls-direct-seg-refs -mno-red-zone -O3 -march=native -mtune=native -ftree-vectorize
     - secure: "hM2VLMlDIEfrK+qaA+mCcs3SvehkzdS1Q/Qwgaoyc2MgvVoBy7jNNrlYdQTw6G2ynwzQr8Fc87aMDl8o0v/i/H1A7EkO3WfVHOxxyrwVuKd5Dmcp3wHj2hEzs3t7XNLMN61Ym32/OtnZAFPjdaiWMuBAWGfesIg7Ez9+Sxr7U9GNcJh8u+g2h/vGVB1ckX1hsGFAhVtUb472tO9FJuk6VYpKlMN4mhE5iB9TLTDV1XKpviYrJkpQTYc1V0rg3BbSzYR/2TMk4TOTIrq/IgG61Mp/B0/GPnAxCI/XBYo7WLR5lLDdEPr4II2LaKbfOdzo3PrY/UhZA4va68JQ6UszibnevyDDGOVqGIf1S7AnjMGezvw06yrAc+PnTzy2ghoY7G/UbZQjlOmcPR3m1KM1YnarP77R1tLCNXiYwGwUW5K8GaVLlXqficKYOsn4roVfsgAhTTGtovwsvVSwO6MITnLAl9XGeZFOhhJ8bdSIuNMQHrobg4UtAQWa4WG7lpMDBCPDSuhAHXjkz6yA7YA9xlabUhxRQDDQ7wxWgmzEJki/FIV2ZuGJvQmXZ/339Xt841GeAp4bl7T5tRj1IIlZvMbXmg8QjjaLMeShqMtsXlecrbkq19Rut5DDOtlNzbYd/yt2hx/gnCAagrf/WndDSgmm/qxXVzTyxE7NfR5st30="
     - secure: "SyyrJPPTxUKxMtWgxcVBprUv0Jl+/Dw4QZCITW2bzz7fyrfXdrJpLav8Un/Yth6ipvScm5WVYTTuh2Rt0uavCpZQpqXRj0hA5yzjK9jlvod8vsfydSSkM+atgWsNoxBs4d12AT9fkLC+3nGE4fVq8esYjXF7K2CzHewdnqTAFUwqR58BLDzfA2uHSAsT3Y3i/vR7V9WpxgT2KbhcCVusayRRnathRGPlDc9WrWKMWiD3ZcuTfUFRQUSUk3H5E0h/PQUGXsd3drNBe7vrhc2eY4apOPUNpdz+C1q2JjIKbtW4vDNHb7dRPoJtFbES9gdpJPbFLikESKGrmF6DtWavzro5BVmJLf0ZIJuPn/UgN1/+NEiurjgYHBS7GRDkuBrwocbW70bxrj2kNsZr1WTbMfn10gKwE/kQO8Pe0INel/ZHm4iDRCNLHoOUh5DginnA/FXOM1LvFZQNvcGmCeDpe6JtRZ0M7aWZ/O/xHBN9+iAzGX3RdY/9IbhwUtMG22DVIUR49a8EfKCdHbxS3rKodb1OeR2gZ82NBI+GOEZr2PZjWSl6XxHs3ZLmORbLJjikV0vfat/AjOM3BDIHdNEOOaV1JIMjfqjPSXcpXAQGlX0lK4QUAH9bJGve3wUfWs9ZyfEkDnzvNiXl7u3fw3i26b/HK/iW76Jor+h6axelYFg="
     - secure: "sYZyC8FK6Q1E6FbRLicHLzwjbNHTsFsyC73OwmHoI5wK64yl5wvg3Og/FA9lUAMTejGxJJ8o7WhI38eQLJXLeyN5iPuC806f2No7Is6wZ8mnHKFoH36/KQ1jXnHJ9LRCUqFvDYLG4r/7dopBdnOHJOgnpd8zVUthzIMnKuqwQuTsQoNkuSuNjs/fQs21iKPo7Foetc57uaSr0IHSgyFb+rw+86yvsSPiH6fgKDN1xG92KpgHinVsfn2wUqKTv/UZNio8tD2JVzHS68w8adC2hxsc+3D2kliaA+zMoc/DlrfFAyizByNRU6JFZ/5jc2gvMvqufa5XcP0FdPo7pTJEqHbQVF4wCJIOX6F5QWJKolsSam2aD79r16lvn7IcdOyNHtGtHknXkW3do2sTP+v8WTlLvD61zo+vKc/Wrw0GrSGENmUvD/UwLGFBV8Hk4rO8JtkZ/LB6uXR66mk1+aAU71s6DCnW29PBVLyXPQ+oAyuq6it50sfdU15XIgTNiAs0SMb7nGRfzs5WvU/i/NFKCw3C6oD/i4RHaU3n/XGxZePNJ8n0kEIu7KLZeig7E2tpfKsUQyJ4d+4rWMIV5+NVYw4cCPnwHOFQd633uZQxGE9wtUQu70rhoSooqjlvqcNLCS78dFqtNU/ifmXGrwZzdv3539Cnj8GS0STyaPDwKZI="
     - secure: "ys3cQL5cvPwpFQbNQOK2OzV/RT+3+Qsdr7Adk6afLh2DdrDgaIPyfZcHDXo3pRLSZtoB+Gd+8FXPGv8Mplq50uTbeK6cRoOV+LmMD9pJ4kUfx/VmG+b5WeMRc+HsO8ADreFJJoZ14UrbaAt7nuypoxS8JwJo0HPbccbheQq8GJeuzN05PT3IRzRbJT7ih+KCAfi749HnD1Xkko94VsICJEcygeiuAMc3BWJlNceLgk2Py/fsLd0ZuFgF44qAVYNkSmVxpxazC49/eD3pxetZXe3UThBe+GJAzh7vNS6vSqzdO/3O0dWI78JdjfgwMO0BS6fRrLnFlLAiVTMAnRb9JBMDS56OyEU/UagNpgrxdXV4IS6IV4NFRFNMsahdLrtsPiDp0KoKEt010S2pr+S04r9ErTvQnFb0F2vdUztgT4obs8qc0L/GW8+f7/jhIthyRRrY9PRI4YywhSMPKwvNysGgLY5pLQ/BC29aXQ8gl/pDJ4CN9BDbUh3wLBPC9P+xqL0yX//UvhGGiT3G94cZ1hjOSDs4t8UWCjT7tznXpofvrqOVRbhYCXI4SoapPUzs/7eRC2P+IlNDV9nPj1YRzmrq9fa6VgT6f+Lv0tfiQsQ4uQYR4zZrJCl2alNC/adoYScrFGdW+FZ9/BydcvVIfnlvh6jXQFb8YUAZcgCzD9o="
